<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="89822" started-at="2015-07-25T16:49:23Z" finished-at="2015-07-25T16:50:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="89822" started-at="2015-07-25T16:49:23Z" finished-at="2015-07-25T16:50:53Z">
      <class name="TestClass1">
        <test-method status="PASS" signature="setup()[pri:0, instance:TestClass1@6791525e]" name="setup" is-config="true" duration-ms="31699" started-at="2015-07-25T22:19:24Z" finished-at="2015-07-25T22:19:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Testcase1()[pri:0, instance:TestClass1@6791525e]" name="Testcase1" duration-ms="41595" started-at="2015-07-25T22:19:55Z" finished-at="2015-07-25T22:20:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [119] but found [114]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [119] but found [114]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at TestClass1.Testcase1(TestClass1.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase1 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:TestClass1@6791525e]" name="teardown" is-config="true" duration-ms="16446" started-at="2015-07-25T22:20:37Z" finished-at="2015-07-25T22:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestClass1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
